[package]
name = "dynstack"
version = "0.1.0"
authors = ["Gui Andrade <gh@archshift.com>"]
description = "A stack for trait objects that minimizes allocations"
license = "MIT"

[dev-dependencies]
criterion = "0.1.2"

[[bench]]
name = "comparisons"
harness = false
